name: build and test
on: [pull_request]

jobs:
  build:
    name: "Build and Test on os: ${{ matrix.os }}. dotnet SDK version: ${{ matrix.dotnet }}"
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        dotnet: ['3.1.200']
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup ${{ matrix.dotnet }} .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Build with dotnet
        run: |
          dotnet build --configuration Debug src/LSATAuthenticationHandler

      - name: Run test in ${{ matrix.os }}
        if: startsWith(matrix.dotnet, '3.1')
        run: dotnet test
